MULE-19139: Mapped Error Type gets replaced by MULE:UNKNOWN
mulesoft/mule-integration-tests pull request #1347
Opened 2021-01-15 17:30 UTC by IvanAndresFritzler

2021-01-19 18:57 UTC, IvanAndresFritzler commented
--validate

2021-01-20 13:12 UTC, elrodro83 requested changes

2021-01-20 13:12 UTC, elrodro83 commented on integration/src/test/java/org/mule/test/integration/exceptions/ValidationModuleErrorHandlingTestCase.java
> +    flowRunner("validationAllWithErrorMapping").run();
why use a queue and an error handler in the flow instead of just using the `runExpecting...` methods?

2021-01-20 13:41 UTC, elrodro83 approved these changes
much better :)

2021-01-20 16:36 UTC, IvanAndresFritzler commented
--validate

2021-01-25 21:13 UTC, elrodro83 approved these changes

2021-01-25 22:18 UTC, merged