MULE-19264: configured parameters are not injected at all
mulesoft/mule-integration-tests pull request #1401
Opened 2021-03-16 18:51 UTC by pabloperalta

2021-03-17 20:14 UTC, elrodro83 requested changes

2021-03-17 20:14 UTC, elrodro83 commented on dsl/src/test/java/org/mule/test/config/ast/ParameterAstTestCase.java
> +  public void parameterGroupNameWithSpacesIsMatchedWithDslWhenItShowsInTheDsl() {
`@Issue`

2021-03-18 12:34 UTC, pabloperalta commented on dsl/src/test/java/org/mule/test/config/ast/ParameterAstTestCase.java
> +  public void parameterGroupNameWithSpacesIsMatchedWithDslWhenItShowsInTheDsl() {
Done

2021-03-23 17:47 UTC, elrodro83 approved these changes

2021-03-23 20:01 UTC, merged