MULE-19928: add tests
mulesoft/mule-integration-tests pull request #1616
Opened 2021-11-12 18:13 UTC by jcgrethe

2021-11-15 13:32 UTC, elrodro83 requested changes

2021-11-15 13:32 UTC, elrodro83 commented on integration/src/test/java/org/mule/test/integration/locator/LazyInitConfigurationComponentLocatorTestCase.java
> +  @Test
allure

2021-11-16 15:17 UTC, elrodro83 approved these changes

2021-11-16 17:33 UTC, jcgrethe commented
--validate

2021-11-16 20:21 UTC, jcgrethe commented
--validate

2021-11-17 12:56 UTC, merged