MULE-19987: Change severity level in validation of expressions
mulesoft/mule-integration-tests pull request #1645
Opened 2021-12-22 14:33 UTC by marianorean

2021-12-22 19:58 UTC, elrodro83 requested changes

2021-12-22 19:58 UTC, elrodro83 commented on integration/src/test/java/org/mule/test/integration/exceptions/CorrelationIdRequiredExpressionsTestCase.java
> +public class CorrelationIdRequiredExpressionsTestCase extends AbstractConfigurationFailuresTestCase {
allure

2021-12-27 12:41 UTC, pabloperalta approved these changes

2021-12-27 15:46 UTC, eze210 approved these changes

2021-12-27 15:53 UTC, merged