W-11500462: Implement the production of On Error components spans
mulesoft/mule-integration-tests pull request #1779
Opened 2022-08-17 17:23 UTC by IvanAndresFritzler

2022-08-18 21:03 UTC, fsgonz requested changes

2022-08-18 21:03 UTC, fsgonz commented on integration/src/test/java/org/mule/test/components/tracing/FlowErrorHandlingTestCase.java
> +import static org.hamcrest.CoreMatchers.equalTo;
static import

2022-08-18 21:03 UTC, fsgonz commented on integration/src/test/java/org/mule/test/components/tracing/TryScopeErrorTracingTestCase.java
> +import static org.hamcrest.Matchers.hasProperty;
static import

2022-08-18 21:16 UTC, fsgonz submitted a review, later dismissed

2022-08-19 18:45 UTC, IvanAndresFritzler commented
--validate

2022-08-23 19:26 UTC, merged