W-12206167: Create a copy of loggingVariables to avoid race conditions
mulesoft/mule-integration-tests pull request #1917
Opened 2022-12-29 17:11 UTC by hyerans

2022-12-29 19:38 UTC, fsgonz requested changes

2022-12-29 19:38 UTC, fsgonz commented on integration/src/test/java/org/mule/logging/TracingLoggingVariableTestCase.java
> +public class TracingLoggingVariableTestCase extends MuleArtifactFunctionalTestCase {
add allure annotations.

2022-12-29 20:31 UTC, hyerans commented on integration/src/test/java/org/mule/logging/TracingLoggingVariableTestCase.java
> +public class TracingLoggingVariableTestCase extends MuleArtifactFunctionalTestCase {
added @Issue allure annotation!

2022-12-30 13:03 UTC, fsgonz approved these changes

2022-12-30 17:40 UTC, hyerans commented
--validate

2022-12-30 18:07 UTC, fsgonz commented
--validate

2022-12-30 18:11 UTC, closed without merging