W-12128703: fix deadlock waiting for previous flow ref to be completed
mulesoft/mule-integration-tests pull request #1949
Opened 2023-01-24 01:40 UTC by hyerans

2023-01-27 00:18 UTC, fsgonz requested changes

2023-01-27 00:18 UTC, fsgonz commented on integration/src/test/java/org/mule/test/sink/TransactionSinkTestCase.java
> +public class TransactionSinkTestCase extends AbstractIntegrationTestCase {
I would add allure annotations with @Issue

2023-01-27 04:20 UTC, hyerans commented on integration/src/test/java/org/mule/test/sink/TransactionSinkTestCase.java
> +public class TransactionSinkTestCase extends AbstractIntegrationTestCase {
added allure annotation!

2023-02-03 11:02 UTC, hyerans commented
--validate

2023-02-03 19:00 UTC, elrodro83 submitted a review, later dismissed

2023-02-06 20:05 UTC, asanguinetti approved these changes

2023-02-07 12:42 UTC, fsgonz approved these changes

2023-02-07 12:44 UTC, asanguinetti approved these changes

2023-02-07 14:25 UTC, merged