W-12356154: [SingleApp] Logging reconfiguration
mulesoft/mule-integration-tests pull request #2249
Opened 2024-01-22 21:53 UTC by fsgonz

2024-01-23 12:29 UTC, elrodro83 requested changes

2024-01-23 12:29 UTC, elrodro83 commented on logging/src/test/java/org/mule/runtime/test/integration/logging/SingleAppModeLoggerTestCase.java
> +  public void log4jLogsInAppSuccessfully() throws Exception {
make clear the scope of what this is testing. According to our talk in slack, this is only testing the reconfiguration.

2024-02-01 20:21 UTC, elrodro83 approved these changes

2024-02-02 00:05 UTC, fsgonz commented
--validate

2024-02-02 03:17 UTC, merged