W-14722908: Avoid locking against MuleContext lifecycle lock when adding registry entries.
mulesoft/mule-integration-tests pull request #2258
Opened 2024-02-02 17:51 UTC by IvanAndresFritzler

2024-02-02 18:28 UTC, elrodro83 approved these changes

2024-02-02 20:44 UTC, fsgonz approved these changes

2024-03-05 15:02 UTC, fsgonz requested changes

2024-03-05 15:02 UTC, fsgonz commented on integration/src/test/java/org/mule/test/integration/lifecycle/ImplicitConfigurationLifeCycleTestCase.java
> +    // Wait until the sub flow signals it's initialization to start stopping the mule context.
it's -> its.

2024-03-05 17:46 UTC, fsgonz approved these changes

2024-03-05 22:02 UTC, merged