W-16761729: add AST validation test case for propery placeholders
mulesoft/mule-integration-tests pull request #2573
Opened 2024-12-12 06:18 UTC by akshaysonvane

2024-12-12 22:02 UTC, elrodro83 requested changes
move to EE to also test components from EE

2024-12-12 22:02 UTC, elrodro83 commented on dsl/src/test/java/org/mule/test/extension/dsl/ASTPropertyPlaceholderValidationTest.java
> +    assertThat(errors, iterableWithSize(0));
use the emptyIterable matcher

2024-12-12 22:02 UTC, elrodro83 commented on dsl/src/test/java/org/mule/test/extension/dsl/ASTPropertyPlaceholderValidationTest.java
> +        .parse("artifact", IOUtils.toInputStream(configFile, StandardCharsets.UTF_8));
standard imports

2024-12-12 22:02 UTC, elrodro83 commented on dsl/src/test/java/org/mule/test/extension/dsl/ASTPropertyPlaceholderValidationTest.java
> +  public void propertyPlaceholderValidation() {
misleading name

2024-12-12 22:02 UTC, elrodro83 commented on dsl/src/test/java/org/mule/test/extension/dsl/ASTPropertyPlaceholderValidationTest.java
> +    ArtifactAst ast = buildArtifactAst(serializationResult);
serializationResult -> appUsingAllCoreComponnets

2024-12-13 02:55 UTC, akshaysonvane commented
Due to the move to EE, closing this PR in favor of [PR](https://github.com/mulesoft/mule-ee-integration-tests/pull/610)

2024-12-13 02:55 UTC, closed without merging